server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: lol1409916
    url: jdbc:postgresql://localhost:5433/registration1
    username: postgres
  jpa:
    hibernate:
#      create-drop; when application is running and stops - it resets and drops everything from registration1 data server
      ddl-auto: create-drop
    properties:
      hibernate:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
